# Generated by Django 2.0 on 2019-01-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aproducts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='a_product',
            name='Ram',
            field=models.TextField(default='None'),
        ),
    ]
