# Generated by Django 2.0 on 2019-01-21 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aproducts', '0002_a_product_ram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='a_product',
            old_name='Card',
            new_name='card',
        ),
    ]
