# Generated by Django 2.0 on 2019-01-22 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aproducts', '0003_auto_20190121_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='a_product',
            old_name='Review_Count',
            new_name='Review_count',
        ),
    ]
