# Generated by Django 2.0 on 2018-11-19 10:25

from django.db import migrations, models
import pproducts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='P_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=39.99, max_digits=20)),
                ('sound', models.TextField(default='good speakers')),
                ('memory', models.TextField(default='2GB')),
                ('camera', models.TextField(default='8MP')),
                ('connectivity', models.TextField(default='None')),
                ('other_features', models.TextField(default='None')),
                ('diplay', models.TextField(default=5.6)),
                ('processor', models.TextField(default=2.0)),
                ('color', models.TextField(default='white')),
                ('image', models.ImageField(blank=True, null=True, upload_to=pproducts.models.upload_image_path)),
            ],
        ),
    ]
