# Generated by Django 2.0 on 2018-11-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pproducts', '0003_auto_20181120_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_product',
            name='Average_Rating',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='p_product',
            name='Review_count',
            field=models.TextField(default='None'),
        ),
    ]
