# Generated by Django 2.0 on 2019-02-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One_GB_Mobiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='one_gb_mobile',
            name='Audio',
            field=models.TextField(default='3.5mm audio jack, MP4/WMV/H.264 player'),
        ),
        migrations.AlterField(
            model_name='one_gb_mobile',
            name='Average_Rating',
            field=models.TextField(default=' 4'),
        ),
        migrations.AlterField(
            model_name='one_gb_mobile',
            name='Browser',
            field=models.TextField(default='HTML5'),
        ),
        migrations.AlterField(
            model_name='one_gb_mobile',
            name='BuiltIn',
            field=models.TextField(default='16GB Built-in'),
        ),
        migrations.AlterField(
            model_name='one_gb_mobile',
            name='Color',
            field=models.TextField(default='Silver, Space Gray, Gold'),
        ),
        migrations.AlterField(
            model_name='one_gb_mobile',
            name='Data',
            field=models.TextField(default='GPRS, Edge, 3G (HSPA 42.2/5.76 Mbps), 4G (LTE-A (2CA) Cat6 300/50 Mbps'),
        ),
        migrations.AlterField(
            model_name='one_gb_mobile',
            name='Dimension',
            field=models.TextField(default='146.2 x 71.3 x 8 mm'),
        ),
        migrations.AlterField(
            model_name='one_gb_mobile',
            name='FourGBand',
            field=models.TextField(default='LTE'),
        ),
        migrations.AlterField(
            model_name='one_gb_mobile',
            name='Front',
            field=models.TextField(default='13 MP, f/1.9, LED flash'),
        ),
        migrations.AlterField(
            model_name='one_gb_mobile',
            name='GPS',
            field=models.TextField(default='Yes + A-GPS support & Glonass, BDS, GALILEO'),
        ),
        migrations.AlterField(
            model_name='one_gb_mobile',
            name='GPU',
            field=models.TextField(default='Mali-T830MP2 '),
        ),
        migrations.AlterField(
            model_name='one_gb_mobile',
            name='Games',
            field=models.TextField(default='built-in + downloadable'),
        ),
        migrations.AlterField(
            model_name='one_gb_mobile',
            name='Main',
            field=models.TextField(default='8MP'),
        ),
        migrations.AlterField(
            model_name='one_gb_mobile',
            name='Messaging',
            field=models.TextField(default=', SMS (threaded view), MMS, Email, Push Email'),
        ),
        migrations.AlterField(
            model_name='one_gb_mobile',
            name='NFC',
            field=models.TextField(default='Yes'),
        ),
        migrations.AlterField(
            model_name='one_gb_mobile',
            name='OperatingSystem',
            field=models.TextField(default='Android v7.1 Nougat'),
        ),
        migrations.AlterField(
            model_name='one_gb_mobile',
            name='Protection',
            field=models.TextField(default='Yes'),
        ),
        migrations.AlterField(
            model_name='one_gb_mobile',
            name='Ram',
            field=models.TextField(default='2GB'),
        ),
        migrations.AlterField(
            model_name='one_gb_mobile',
            name='Resolution',
            field=models.TextField(default='720 x 1280 Pixels (~282 PPI) '),
        ),
        migrations.AlterField(
            model_name='one_gb_mobile',
            name='Review_count',
            field=models.TextField(default='90'),
        ),
        migrations.AlterField(
            model_name='one_gb_mobile',
            name='SIM',
            field=models.TextField(default='Single SIM (Nano-SIM)  '),
        ),
        migrations.AlterField(
            model_name='one_gb_mobile',
            name='Size',
            field=models.TextField(default='5.5 inches'),
        ),
        migrations.AlterField(
            model_name='one_gb_mobile',
            name='ThreeGBand',
            field=models.TextField(default='HSDPA 850 / 900 / 1700(AWS) / 1900 / 2100 '),
        ),
        migrations.AlterField(
            model_name='one_gb_mobile',
            name='Torch',
            field=models.TextField(default='Yes'),
        ),
        migrations.AlterField(
            model_name='one_gb_mobile',
            name='TwoGBand',
            field=models.TextField(default='SIM1: GSM 850 / 900 / 1800 / 1900 SIM2: GSM 850 / 900 / 1800 / 1900  '),
        ),
        migrations.AlterField(
            model_name='one_gb_mobile',
            name='UIBuild',
            field=models.TextField(default='TouchWiz UI'),
        ),
        migrations.AlterField(
            model_name='one_gb_mobile',
            name='USB',
            field=models.TextField(default='microUSB 2.0'),
        ),
        migrations.AlterField(
            model_name='one_gb_mobile',
            name='Weight',
            field=models.TextField(default='148g'),
        ),
        migrations.AlterField(
            model_name='one_gb_mobile',
            name='Wifi',
            field=models.TextField(default='Wi-Fi 802.11 a/b/g/n/ac, dual-band, hotspot'),
        ),
        migrations.AlterField(
            model_name='one_gb_mobile',
            name='card',
            field=models.TextField(default='Yes'),
        ),
    ]
