# Generated by Django 2.0 on 2019-03-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0002_accessories_image'),
        ('carts', '0004_auto_20190302_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='accessory',
            field=models.ManyToManyField(blank=True, to='accessories.Accessories'),
        ),
    ]
